# The issue

- Getting the message "Sorry, something went wrong. Reload?" when viewing an *.ipynb on a GitHub blob page.
```diff
+ Probably a problem with the GitHub notebook viewing tool - sometimes github fails to render the ipynb notebooks, 
+ I believe that is some temporary (and recurring) issue with their backend

- A workaround

+ Try to open that notebook that you want using nbviewer online, you don't need to install it.
```
### Open "https://nbviewer.jupyter.org/"
### Paste this link - https://github.com/shuklasaharsh/IOT_Temperatur_ESP8266/blob/main/Notebook/Time%20predictor%20backend.ipynb

## OR
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/shuklasaharsh/IOT_Temperatur_ESP8266/blob/main/Notebook/Time%20predictor%20backend.ipynb)

### OR

[![Open in NBViewer](https://user-images.githubusercontent.com/2791223/29387450-e5654c72-8294-11e7-95e4-090419520edb.png)](https://nbviewer.jupyter.org/github/shuklasaharsh/IOT_Temperatur_ESP8266/blob/main/Notebook/Time%20predictor%20backend.ipynb)

```diff
+ The Notebook should be visible.
```
